redis:
    image: redis:latest
    ports:
        - "6379:6379"
    expose:
        - "6379"
app0:
    build: .
    links:
        - redis
app1:
    build: .
    links:
        - redis
app2:
    build: .
    links:
        - redis
app3:
    build: .
    links:
        - redis
app4:
    build: .
    links:
        - redis
get_errors:
    build: .
    links:
        - redis
    command: /app/main getErrors
